/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: Homless_Models (https://sketchfab.com/hl_models)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rust-space-suit-c9b05b4878d64c68945ba8858c523a68
Title: Rust Space Suit
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('astronaut/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={3} position={[-3.5, -3, 0.4]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh geometry={nodes.Object_6.geometry} material={materials.SuitMat} skeleton={nodes.Object_6.skeleton} />
          <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.BackpackMat} skeleton={nodes.Object_7.skeleton} />
          <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.HelmetMat} skeleton={nodes.Object_8.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('astronaut/scene.gltf')
