/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: rsatenza (https://sketchfab.com/rsatenza)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/discovery-space-shuttle-23c579b845e841c9b6c6d59bd5725bb6
Title: Discovery Space Shuttle
*/

import React, { useRef, useEffect, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import gsap from 'gsap';
import ScrollTrigger from 'gsap/ScrollTrigger';

export function Model(props) {
  const { nodes, materials } = useGLTF('/ship/scene.gltf')
  const model = useRef(null);

  useEffect(() => {
    let ctx = gsap.context(() => {

      ScrollTrigger.create({
        trigger: ".shipTrigger",
        start: "top bottom",
        end: "bottom bottom",
        onUpdate: (self) => {
          if (model && self.progress <= 0.5) {
            model.current.rotation.y = -3 * 3.14 * self.progress;
            model.current.rotation.x = 0;
            model.current.position.x = -8 * self.progress;
            model.current.position.y = -0.4 * self.progress;
            model.current.position.z = 0.4 * self.progress
          }
        }
      })

    },)

    return () => ctx.revert();
  }, [])

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 3]} scale={2.5} position={[0, 0, 0]} ref={model}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Transbordador_Slot__6} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.Metal_Detalle} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.Coraza} />
          <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.Cristal} />
          <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.Metal_Base} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/ship/scene.gltf');
